use_frameworks!

target 'UIRadioButton_Example' do
  pod 'UIRadioButton', :path => '../'

  target 'UIRadioButton_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
