use_frameworks!

target 'UIRadioButton_Example' do
  pod 'UIRadioButton', :path => '../'

  target 'UIRadioButton_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    
  end
end
